//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMDonVi
    {
        public int Id { get; set; }
        public int STT { get; set; }
        public string MaDonVi { get; set; }
        public string TenDonVi { get; set; }
        public string GhiChu { get; set; }
        public string LoaiDonVi { get; set; }
        public Nullable<int> IDDVCha { get; set; }
        public string NhomLoai { get; set; }
        public string SoDiemTruong { get; set; }
        public string TenLanhDao { get; set; }
        public string DiaChi { get; set; }
        public string IDTinh { get; set; }
        public string IDHuyen { get; set; }
        public string IDXa { get; set; }
        public string Email { get; set; }
        public string DienThoai { get; set; }
        public string Fax { get; set; }
        public string Website { get; set; }
        public string LoaiHinh { get; set; }
        public Nullable<int> IDLoaiTruong { get; set; }
        public string ThongTinKhac { get; set; }
        public Nullable<bool> FInUse { get; set; }
        public string TTGui { get; set; }
    }
}
