//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDoituongThanhtich
    {
        public long Id { get; set; }
        public Nullable<long> IdDoituong { get; set; }
        public Nullable<System.DateTime> Ngaytao { get; set; }
        public Nullable<int> IdTieuchi { get; set; }
        public Nullable<double> Diem { get; set; }
        public string Ghichu { get; set; }
    }
}
