//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDoituong
    {
        public long Id { get; set; }
        public string Hodem { get; set; }
        public string Ten { get; set; }
        public string Gioitinh { get; set; }
        public Nullable<System.DateTime> Ngaysinh { get; set; }
        public string Dantoc { get; set; }
        public string SoCMND { get; set; }
        public string Diachi { get; set; }
        public string Sdt { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Chucvu { get; set; }
        public string Vitri { get; set; }
        public string Ghichu { get; set; }
        public Nullable<int> IdDonvi { get; set; }
        public Nullable<int> Loai { get; set; }
    }
}
