//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDanhmuc
    {
        public int Id { get; set; }
        public Nullable<int> STT { get; set; }
        public string Ma { get; set; }
        public string Ten { get; set; }
        public string Viettat { get; set; }
        public string Maloai { get; set; }
        public Nullable<int> IdCha { get; set; }
        public string TTKhac1 { get; set; }
        public string TTKhac2 { get; set; }
        public string TTKhac3 { get; set; }
        public string Ghichu { get; set; }
        public Nullable<bool> FInUse { get; set; }
    }
}
