//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDonviPhongtrao
    {
        public long Id { get; set; }
        public Nullable<int> IdPhongtrao { get; set; }
        public Nullable<int> IdDonvi { get; set; }
        public Nullable<int> Trangthai { get; set; }
        public string Ghichu { get; set; }
    }
}
