//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGiaytoKhenthuong
    {
        public long Id { get; set; }
        public Nullable<long> IdDoituongKhenthuong { get; set; }
        public Nullable<int> IdGiayto { get; set; }
        public string Tentep { get; set; }
        public string Duongdan { get; set; }
        public Nullable<int> Nam { get; set; }
        public string Loai { get; set; }
    }
}
