//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuyetdinh
    {
        public int Id { get; set; }
        public Nullable<int> IdDonvi { get; set; }
        public Nullable<int> Nam { get; set; }
        public string SoQD { get; set; }
        public string Ten { get; set; }
        public Nullable<System.DateTime> NgayQD { get; set; }
        public string Noidung { get; set; }
        public string Duongdan { get; set; }
        public string Ghichu { get; set; }
    }
}
