//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblThanhvienTapthe
    {
        public long Id { get; set; }
        public Nullable<long> IdTapthe { get; set; }
        public Nullable<long> IdCanhan { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<long> IdKhenthuong { get; set; }
    }
}
