//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongBao
    {
        public long Id { get; set; }
        public string Link { get; set; }
        public string NoiDung { get; set; }
        public string NguoiDoc { get; set; }
        public string DonViNhan { get; set; }
        public Nullable<bool> FInUse { get; set; }
        public string NguoiGui { get; set; }
        public Nullable<System.DateTime> NgayGui { get; set; }
        public Nullable<int> Loai { get; set; }
        public Nullable<int> TrangThai { get; set; }
    }
}
