//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public long Id { get; set; }
        public Nullable<long> STT { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> FInUse { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Mobile { get; set; }
        public string HoTen { get; set; }
        public string DiaChi { get; set; }
        public string IDTinh { get; set; }
        public string IDHuyen { get; set; }
        public string IDXa { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string ChucVu { get; set; }
        public string Avatar { get; set; }
        public Nullable<long> IDDonVi { get; set; }
        public Nullable<bool> DaiDien { get; set; }
        public Nullable<int> LockScreenTime { get; set; }
        public Nullable<bool> IsOnline { get; set; }
        public string ConnId { get; set; }
    }
}
